/**
 * Copyright (c) MuleSoft, Inc. All rights reserved. http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.md file.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.connector.boxnet;

import org.junit.Test;
import org.mule.modules.boxnet.BoxUtils;
import org.mule.transformer.codec.Base64Encoder;


/**
 * TODO: actually test the methods. This is bocked until the MUnit module is released
 * @author mariano.gonzalez@mulesoft.com
 *
 */
public class BoxNetModuleTest {

	@Test
	public void base64() throws Exception {
		String hello = "hello world!";
		String encoded = (String) new Base64Encoder().doTransform(hello, "UTF-8");
		String decoded = BoxUtils.decodeBase64(encoded, "UTF-8");
		
		assert hello.equals(decoded) : "post encoding strings do not match. Obtained: " + decoded;
	}
	
	public void validateFolder() {
		BoxUtils.validateTarget("folder");
		BoxUtils.validateTarget("file");
		
		try {
			BoxUtils.validateTarget("something else");
			assert false : "failure expected";
		} catch (IllegalArgumentException e) {
			assert true;
		}
	}
	
}
