/**
 * Mule Development Kit
 * Copyright 2010-2011 (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.connector.boxnet;

import org.junit.Test;
import org.mule.modules.boxnet.BoxNetModule;
import org.mule.transformer.codec.Base64Encoder;


/**
 * TODO: actually test the methods. This is bocked until the MUnit module is released
 * @author mariano.gonzalez@mulesoft.com
 *
 */
public class BoxNetModuleTest {

	@Test
	public void base64() throws Exception {
		String hello = "hello world!";
		String encoded = (String) new Base64Encoder().doTransform(hello, "UTF-8");
		String decoded = BoxNetModule.decodeBase64(encoded, "UTF-8");
		
		assert hello.equals(decoded) : "post encoding strings do not match. Obtained: " + decoded;
	}
	
	public void validateFolder() {
		 BoxNetModule.validateTarget("folder");
		 BoxNetModule.validateTarget("file");
		
		try {
			BoxNetModule.validateTarget("something else");
			assert false : "failure expected";
		} catch (IllegalArgumentException e) {
			assert true;
		}
	}
	
}
